spring.application.name=docuflow
server.port=8080

# PostgreSQL Bağlantısı
spring.datasource.url=jdbc:postgresql://localhost:5432/ebelge_db
spring.datasource.username=postgres
spring.datasource.password=123456

# JPA / Hibernate Yapılandırması
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect